### ISSUE TITLE
Ingress support

### ISSUE THREAD

**Issue by MiguelAngelLV** [hassio-addons/addon-sonarr#8]
# Problem/Motivation

Sonarr addon not support ingress 

## Expected behavior

Access to sonarr by ingress without port foward 

## Actual behavior

Access to sonarr use port instead ingress 

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
That is very problematic to do, as the settings can be changed in the UI of Sonarr that will make things incompatible.

Hence, it doesn't have it. Use an iframe panel instead.

Closing this issue, as it is a feature request.

../Frenck
